// Every point of interest in the game, served from /api/places.
//
// pos      — position on our compressed map, north-up: [x (east), y (north)]
// radius   — how close (world units) the player must be for the info icon to appear
// model    — key of the 3D landmark model built on the client (or null)
// body     — a few short paragraphs; facts — quick label/value pairs
//
// Writing style: warm, plain English for curious adults — diaspora and students.

export const categories = {
  heritage: { label: 'Heritage', color: '#c77d1a', icon: '🏛️' },
  faith: { label: 'Faith', color: '#1f9d6b', icon: '🕌' },
  neighbourhood: { label: 'Neighbourhoods', color: '#6a4fc9', icon: '🏘️' },
  street: { label: 'Streets & Bazaars', color: '#d6336c', icon: '🛣️' },
  food: { label: 'Food', color: '#e8590c', icon: '🍢' },
  sea: { label: 'Sea & Shore', color: '#1c7ed6', icon: '🌊' },
  modern: { label: 'Modern City', color: '#4a6178', icon: '🏙️' },
};

export const places = [
  // ───────────────────────────── Heritage ─────────────────────────────
  {
    id: 'mazar-e-quaid',
    name: 'Mazar-e-Quaid',
    urdu: 'مزارِ قائد',
    category: 'heritage',
    area: 'Jamshed Quarters',
    pos: [18, 112],
    radius: 30,
    model: 'mazar',
    tagline: 'Where the man who founded Pakistan is buried.',
    body: [
      "This white marble mausoleum stands on a raised platform in the middle of wide gardens, and it is the most recognisable building in Karachi. It holds the tomb of Muhammad Ali Jinnah, the Quaid-e-Azam ('Great Leader'), who led the campaign for Pakistan. He died in Karachi in September 1948, thirteen months after independence.",
      'The architect, Yahya Merchant, designed it with sweeping, curved Moorish arches and copper grilles. It was completed in 1970 after years of arguments over the design. Inside, a four-tiered crystal chandelier, a gift from China, hangs over the cenotaph. The actual graves are in a crypt beneath it.',
      "Jinnah is not the only person buried here. His sister Fatima Jinnah lies nearby. She was a formidable politician in her own right, and in 1965 she challenged the military ruler Ayub Khan for the presidency, in an election many still believe was rigged. Liaquat Ali Khan, Pakistan's first prime minister, assassinated in 1951, is also buried here.",
    ],
    facts: [
      ['Completed', '1970'],
      ['Architect', 'Yahya Merchant'],
      ['Also buried here', 'Fatima Jinnah, Liaquat Ali Khan'],
    ],
    didYouKnow:
      'Jinnah was born only a few kilometres away, in Wazir Mansion in Kharadar. On national days such as 14 August and 25 December (his birthday), cadets hold a formal changing of the guard at the mausoleum.',
  },
  {
    id: 'frere-hall',
    name: 'Frere Hall',
    urdu: 'فریئر ہال',
    category: 'heritage',
    area: 'Civil Lines',
    pos: [-62, -50],
    radius: 22,
    model: 'frereHall',
    tagline: 'A Venetian Gothic hall with a painted sky inside.',
    body: [
      "Frere Hall was built in 1865 and named after Sir Bartle Frere, a British Commissioner of Sindh who worked hard to make Karachi a major port. It looks like a piece of Venice dropped into the city, with yellowish Karachi limestone, bands of red and grey sandstone, pointed arches and a central tower.",
      "It started life as a town hall. Today it houses the Liaquat Memorial Library and a gallery whose ceiling was painted by Sadequain, one of Pakistan's best-loved artists. His mural, Arz-o-Samawat ('The Earth and the Heavens'), was still unfinished when he died in 1987.",
      "The lawns around the hall were once called Queen's Lawn and are now Bagh-e-Jinnah. Families come here for picnics and wedding photos, and on Sundays there is a sprawling second-hand book bazaar.",
    ],
    facts: [
      ['Built', '1865'],
      ['Style', 'Venetian Gothic'],
      ['Named after', 'Sir Bartle Frere'],
    ],
    didYouKnow:
      "For years the hall sat behind security barriers, because the US Consulate was right next door during the tense 2000s. The consulate moved away in 2011, and the gardens slowly came back to life as a public space.",
  },
  {
    id: 'empress-market',
    name: 'Empress Market',
    urdu: 'ایمپریس مارکیٹ',
    category: 'heritage',
    area: 'Saddar',
    pos: [-56, 26],
    radius: 24,
    model: 'empressMarket',
    tagline: 'A Victorian clock tower above a maze of spices, fruit and everything else.',
    body: [
      "Empress Market was named after Queen Victoria, Empress of India, and built between 1884 and 1889. Its Gothic clock tower, more than 40 metres tall, was meant to be visible across Saddar, and it still is.",
      'Inside, it is Karachi at full volume. There are mountains of dried fruit, sacks of red chillies and turmeric, butchers and fishmongers, sellers of birds and kittens, and shopkeepers who insist you taste something before you buy it.',
      "According to local accounts, the site was once where Indian soldiers who rose against the British in 1857 were executed, which gives the cheerful bustle a darker backstory. In 2018 a court-ordered anti-encroachment drive demolished hundreds of shops that had grown up around the market. That opened up the view of the building again, but it also cost many traders their livelihoods.",
    ],
    facts: [
      ['Built', '1884–1889'],
      ['Designed by', 'James Strachan'],
      ['Clock tower', 'over 40 m tall'],
    ],
    didYouKnow:
      'The market is still roughly organised by trade: spices and dry fruit in one part, meat and fish in another, and pets and birds tucked into the lanes outside.',
  },
  {
    id: 'merewether-tower',
    name: 'Merewether Clock Tower',
    urdu: 'میری ویدر ٹاور',
    category: 'heritage',
    area: 'Old City',
    pos: [-160, 0],
    radius: 20,
    model: 'merewether',
    tagline: 'A Gothic tower marking the spot where old Karachi meets the port.',
    body: [
      'This square Gothic clock tower was built between 1884 and 1892 in memory of Sir William Merewether, Commissioner of Sindh from 1867 to 1877. It stands where M.A. Jinnah Road meets I.I. Chundrigar Road, right at the edge of the old city.',
      "All around it is the city's oldest trading quarter: Kharadar and Mithadar, the cloth and grain markets of Jodia Bazaar and Bolton Market, and the roads down to the docks. Before the British took Karachi in 1839, the walled merchant town of Kolachi stood here.",
      'Today the tower stands in a sea of honking traffic. Stop for a minute, though, and you can see the layers of the city: Victorian stone, older merchant houses, and the newer tangle of shops and signboards.',
    ],
    facts: [
      ['Built', '1884–1892'],
      ['Height', 'about 31 m'],
      ['Named after', 'Sir William Merewether'],
    ],
    didYouKnow:
      "Kharadar and Mithadar are named after the gates of the 18th-century walled town of Kolachi. Khara Dar, the 'salty gate', faced the sea, and Mitha Dar, the 'sweet gate', faced the fresh water of the Lyari River.",
  },
  {
    id: 'wazir-mansion',
    name: 'Wazir Mansion',
    urdu: 'وزیر مینشن',
    category: 'heritage',
    area: 'Kharadar',
    pos: [-188, -4],
    radius: 18,
    model: 'wazirMansion',
    tagline: "The house where Pakistan's founder was born.",
    body: [
      'Muhammad Ali Jinnah was born on 25 December 1876 in this modest three-storey stone house in Kharadar. His family were Gujarati Khoja merchants who had moved to Karachi for its booming trade.',
      'The government acquired the building in the early 1950s and turned it into a national monument and small museum. It holds family furniture, some of his law books, and personal belongings.',
      "Kharadar itself is one of Karachi's oldest neighbourhoods. It has narrow lanes, carved wooden balconies, mosques and imambargahs, and the community halls of the Ismaili, Bohri and Memon communities whose merchants built much of the city's trade.",
    ],
    facts: [
      ['Born here', 'Muhammad Ali Jinnah, 1876'],
      ['Today', 'National monument & museum'],
      ['Neighbourhood', 'Kharadar'],
    ],
    didYouKnow:
      "Some historians argue that Jinnah was actually born in Jhirk, a small town near Thatta, and that his family moved to Karachi soon after. Karachi's claim is the official one, but the debate still comes up from time to time.",
  },
  {
    id: 'mohatta-palace',
    name: 'Mohatta Palace',
    urdu: 'موہٹا پیلس',
    category: 'heritage',
    area: 'Clifton',
    pos: [-82, -88],
    radius: 22,
    model: 'mohatta',
    tagline: 'A pink stone palace built for the sea breeze.',
    body: [
      'In 1927 Shivratan Chandraratan Mohatta, a Marwari businessman from Rajasthan, built this summer palace in Clifton. The story goes that his wife was unwell and her doctors recommended sea air. The architect, Agha Ahmed Hussain from Jaipur, used pink Jodhpur stone and local yellow stone to create a little Rajasthani palace with domes and balconies.',
      "Mohatta left for India after Partition in 1947, and the palace became government property. It briefly housed the Foreign Ministry. From 1964 it was the home of Fatima Jinnah, the founder's sister, and after her death another sister, Shireen, lived here until 1980.",
      'After years of legal tangles it reopened in 1999 as a museum, and it now hosts exhibitions on art, textiles and the history of Sindh.',
    ],
    facts: [
      ['Built', '1927'],
      ['Architect', 'Agha Ahmed Hussain'],
      ['Museum since', '1999'],
    ],
    didYouKnow:
      'Local legend says a tunnel once ran from the palace to a Hindu temple near the shore, so the family could go to prayers unseen. Nobody has ever found it.',
  },
  {
    id: 'chaukhandi-tombs',
    name: 'Chaukhandi Tombs',
    urdu: 'چوکھنڈی کے مقبرے',
    category: 'heritage',
    area: 'Off the National Highway',
    pos: [395, 30],
    radius: 22,
    model: 'chaukhandi',
    tagline: 'Carved sandstone graves on the old road east.',
    body: [
      "About 29 km east of central Karachi, just off the National Highway, is a graveyard of carved sandstone tombs dating mostly from the 15th to the 18th centuries. Most belong to the Baloch and Jokhio tribes who lived in the region. (In our miniature Karachi they're a lot closer!)",
      "The graves are stacked like small stepped pyramids and covered in remarkably detailed carving: rosettes and geometric patterns everywhere, horsemen, swords and shields on men's graves, and jewellery such as bangles and necklaces on women's.",
      "The site is on UNESCO's tentative list of World Heritage Sites, but wind, salt and creeping development are slowly wearing the carvings away.",
    ],
    facts: [
      ['Period', '15th–18th centuries'],
      ['Material', 'Yellow sandstone'],
      ['Status', 'UNESCO tentative list'],
    ],
    didYouKnow:
      "The name 'Chaukhandi' is often linked to the four-cornered canopies, raised on pillars, that sit over some of the graves.",
  },

  // ────────────────────────────── Faith ──────────────────────────────
  {
    id: 'st-patricks-cathedral',
    name: "St. Patrick's Cathedral",
    urdu: 'سینٹ پیٹرکس کیتھیڈرل',
    category: 'faith',
    area: 'Saddar',
    pos: [-8, 14],
    radius: 20,
    model: 'stPatricks',
    tagline: "Gothic arches at the heart of Karachi's Catholic community.",
    body: [
      "St. Patrick's was consecrated in 1881. It is one of the largest churches in Pakistan, built in a Gothic Revival style with a vaulted nave that holds around 1,500 people, and it is the seat of the Archdiocese of Karachi.",
      'Saddar was once home to a large Goan Catholic community. They came from Portuguese-ruled Goa during British times and worked as clerks, teachers, musicians and cooks. Many of their stone houses, schools and churches still stand nearby, even though much of the community has since emigrated.',
      'In front of the cathedral stands the Monument to Christ the King, a tall column topped with a statue, raised in 1931.',
    ],
    facts: [
      ['Consecrated', '1881'],
      ['Style', 'Gothic Revival'],
      ['Holds', 'about 1,500 people'],
    ],
    didYouKnow:
      "Midnight mass here on Christmas Eve draws huge crowds. Since 25 December is also Jinnah's birthday and a public holiday, plenty of non-Christian Karachiites come along for the lights and the carols.",
  },
  {
    id: 'tooba-mosque',
    name: 'Tooba Mosque (Gol Masjid)',
    urdu: 'طوبیٰ مسجد',
    category: 'faith',
    area: 'DHA',
    pos: [110, -58],
    radius: 26,
    model: 'tooba',
    tagline: 'One enormous dome and one slender minaret.',
    body: [
      "The Tooba Mosque in Defence was built in 1969 and is better known as the Gol Masjid, or Round Mosque. It is famous for its single white marble dome, about 72 metres across, which rests on a low circular wall with no pillars inside.",
      'It was designed by the architect Babar Hamid Chauhan and the engineer Zaheer Haider Naqvi. The prayer hall holds around 5,000 worshippers, and a 70-metre minaret rises beside it.',
      'The acoustics under the dome are remarkable. Speak softly against the wall on one side and someone on the far side can hear you.',
    ],
    facts: [
      ['Built', '1969'],
      ['Dome', 'about 72 m across'],
      ['Minaret', 'about 70 m'],
    ],
    didYouKnow:
      "For many years it was described as the largest single-dome mosque in the world.",
  },
  {
    id: 'abdullah-shah-ghazi',
    name: 'Shrine of Abdullah Shah Ghazi',
    urdu: 'مزار عبداللہ شاہ غازی',
    category: 'faith',
    area: 'Clifton',
    pos: [-72, -112],
    radius: 20,
    model: 'shrine',
    tagline: "Karachi's patron saint, keeping watch over the sea.",
    body: [
      'On a small hill near the Clifton shore stands the green-and-white shrine of Abdullah Shah Ghazi. He was an 8th-century Sufi saint and a descendant of the Prophet Muhammad who, according to tradition, came to Sindh around 760 CE.',
      "Many Karachiites believe he protects the city from the sea. When a cyclone veers away from the coast, people will tell you it was his doing. Thousands visit every week to pray, tie threads for wishes, hand out food and listen to qawwali, and his annual urs (death anniversary festival) fills the surrounding streets.",
      "In October 2010 two suicide bombers attacked the shrine, killing several people. It was part of a wave of attacks on Sufi shrines by militants who reject these traditions. Devotees kept coming back anyway.",
    ],
    facts: [
      ['Saint', 'Abdullah Shah Ghazi, 8th century'],
      ['Known for', 'Qawwali, langar (free food), urs'],
      ['Colours', 'Green and white'],
    ],
    didYouKnow:
      'There is a freshwater spring at the foot of the hill, remarkably close to the salty sea. Devotees consider it one of the saint\'s miracles.',
  },

  // ─────────────────────────── Modern City ───────────────────────────
  {
    id: 'teen-talwar',
    name: 'Teen Talwar',
    urdu: 'تین تلوار',
    category: 'modern',
    area: 'Clifton',
    pos: [-38, -70],
    radius: 20,
    model: 'teenTalwar',
    tagline: 'Three white swords at the gateway to Clifton.',
    body: [
      "The Three Swords monument was built in 1974 in a roundabout at the entrance to Clifton. Each sword carries one word of Jinnah's motto: Unity, Faith and Discipline.",
      "It was commissioned during Zulfikar Ali Bhutto's government. Critics have long pointed out that the sword was also the election symbol of his Pakistan Peoples Party at the time. Depending on who you ask, it is either a civic monument or a giant campaign poster.",
      'Today it is simply a landmark. People use it as a meeting point, and it is a backdrop for celebrations, protests and political rallies.',
    ],
    facts: [
      ['Built', '1974'],
      ['Motto', 'Unity, Faith, Discipline'],
      ['Era', 'Zulfikar Ali Bhutto government'],
    ],
    didYouKnow:
      "Karachiites name roundabouts after whatever stands in the middle. There's Teen Talwar (Three Swords), Do Talwar (Two Swords) just down the road, and many more chowrangis known only by their monuments.",
  },
  {
    id: 'bahria-icon-tower',
    name: 'Bahria Icon Tower',
    urdu: 'بحریہ آئیکن ٹاور',
    category: 'modern',
    area: 'Clifton',
    pos: [-28, -100],
    radius: 22,
    model: 'bahriaIcon',
    tagline: 'The tallest building in Pakistan, and a lightning rod for controversy.',
    body: [
      "Bahria Icon Tower rises about 273 metres over Clifton, making it the tallest building in Pakistan. It was built by Bahria Town, the property empire of the tycoon Malik Riaz, and its glass sides catch the sunlight over the sea. You can see it from much of the city.",
      "Its construction was dogged by controversy. Questions were raised in court about how public land beside the shrine of Abdullah Shah Ghazi and the Bagh Ibn-e-Qasim park ended up hosting a private skyscraper. Bahria Town has been at the centre of several of Pakistan's biggest land disputes.",
      'For many Karachiites it is simply a new landmark, and a sign of how a skyline once ruled by colonial clock towers and minarets is now reaching upward in glass.',
    ],
    facts: [
      ['Height', 'about 273 m'],
      ['Developer', 'Bahria Town'],
      ['Built', '2010s'],
    ],
    didYouKnow:
      "For more than 30 years Pakistan's tallest building was Habib Bank Plaza on I.I. Chundrigar Road, at about 100 metres. The Icon is nearly three times as tall.",
  },
  {
    id: 'national-stadium',
    name: 'National Stadium',
    urdu: 'نیشنل اسٹیڈیم',
    category: 'modern',
    area: 'Karsaz',
    pos: [180, 125],
    radius: 30,
    model: 'stadium',
    tagline: "Where Karachi's cricket dreams play out.",
    body: [
      "The National Stadium opened in 1955 and hosted Pakistan's first home Test match against India that same year. It went on to become a fortress: Pakistan played 34 Tests here without a single defeat, until England won in near-darkness in December 2000.",
      "After gunmen attacked Sri Lanka's team bus in Lahore in 2009, international cricket stayed away from Pakistan for a decade. When Test cricket returned to Karachi in December 2019, against Sri Lanka, it was celebrated as a homecoming. The stadium now packs out for Pakistan Super League matches.",
      'On match days the whole area hums with horns, painted faces, flag sellers and the smell of samosas.',
    ],
    facts: [
      ['Opened', '1955'],
      ['Capacity', 'about 34,000'],
      ['Home team', 'Karachi Kings (PSL)'],
    ],
    didYouKnow:
      'Street cricket is a way of life in Karachi. On any evening you can find tape-ball matches in lanes, parking lots and on rooftops, and a lot of Pakistani fast bowlers learned their trade that way.',
  },
  {
    id: 'jinnah-airport',
    name: 'Jinnah International Airport',
    urdu: 'جناح انٹرنیشنل ایئرپورٹ',
    category: 'modern',
    area: 'Shahrah-e-Faisal',
    pos: [372, 200],
    radius: 32,
    model: 'airport',
    tagline: "One of Pakistan's busiest gateways, with a past involving airships.",
    body: [
      "Karachi's aviation story began at Drigh Road in the 1920s, when the British built one of the world's largest airship hangars here for an imperial airship service. The airship R101 was meant to fly to Karachi in 1930, but it crashed in France on the way and never arrived. The giant hangar stood mostly unused for decades before it was demolished.",
      "The modern Jinnah Terminal opened in 1992. For many Pakistanis abroad it is their first taste of home: the wall of heat, crowds of relatives pressed against the barriers, and garlands of roses.",
      'In June 2014 militants attacked the airport, and flights were suspended while security forces fought them off.',
    ],
    facts: [
      ['Jinnah Terminal', '1992'],
      ['Airport code', 'KHI'],
      ['Reached by', 'Shahrah-e-Faisal'],
    ],
    didYouKnow:
      'Karachi was a stop on the earliest airline route from Britain to India. Imperial Airways passengers were landing here from London in 1929.',
  },
  {
    id: 'university-of-karachi',
    name: 'University of Karachi',
    urdu: 'جامعہ کراچی',
    category: 'modern',
    area: 'University Road',
    pos: [238, 250],
    radius: 26,
    model: 'kuGate',
    tagline: "Pakistan's biggest campus, and a cradle of the city's politics.",
    body: [
      'The University of Karachi was founded in 1951 and moved to its huge campus off University Road around the end of that decade. Today it teaches tens of thousands of students and is home to respected research centres such as the H.E.J. Research Institute of Chemistry.',
      "The campus has also been a political battleground. In 1978 a student named Altaf Hussain founded the All Pakistan Muhajir Students Organisation here. Six years later it grew into the Muhajir Qaumi Movement (MQM), which dominated Karachi's politics for three decades, both in power and in violent conflict.",
      "In April 2022 a suicide bombing near the university's Confucius Institute killed three Chinese teachers and their Pakistani driver. It was a reminder that the campus is never far from the country's wider tensions.",
    ],
    facts: [
      ['Founded', '1951'],
      ['Campus', 'over 1,200 acres'],
      ['Landmark', 'Silver Jubilee Gate'],
    ],
    didYouKnow:
      "The Silver Jubilee Gate at the campus entrance was built to mark the university's 25th anniversary, and it is one of University Road's best-known landmarks.",
  },

  // ──────────────────────── Streets & Bazaars ────────────────────────
  {
    id: 'ii-chundrigar-road',
    name: 'I.I. Chundrigar Road',
    urdu: 'آئی آئی چندریگر روڈ',
    category: 'street',
    area: 'Business District',
    pos: [-110, -26],
    radius: 22,
    model: 'habibPlaza',
    modelPos: [-100, -12],
    tagline: "Pakistan's Wall Street.",
    body: [
      "This road used to be called McLeod Road. It is now named after Ismail Ibrahim Chundrigar, who was Pakistan's prime minister for just under two months in 1957. He was one of seven prime ministers in the country's first eleven years, before the first military coup in 1958.",
      "It is the country's financial spine. The State Bank of Pakistan, the head offices of major banks and insurance companies, and the Jang newspaper group all line the road, and the Pakistan Stock Exchange is just around the corner.",
      'Its most famous building is Habib Bank Plaza, finished in 1972. At about 100 metres, it was the tallest building in Pakistan for more than thirty years.',
    ],
    facts: [
      ['Old name', 'McLeod Road'],
      ['Named after', 'I.I. Chundrigar, PM in 1957'],
      ['Landmark', 'Habib Bank Plaza (1972)'],
    ],
    didYouKnow:
      "The State Bank of Pakistan was inaugurated by Jinnah himself in July 1948. Its old building now houses a museum of coins, banknotes and art.",
  },
  {
    id: 'ma-jinnah-road',
    name: 'M.A. Jinnah Road',
    urdu: 'ایم اے جناح روڈ',
    category: 'street',
    area: 'Old City to Numaish',
    pos: [-100, 30],
    radius: 22,
    model: 'kmc',
    modelPos: [-104, 46],
    tagline: "Old Bunder Road, the city's original main street.",
    body: [
      "This road was once called Bunder Road, meaning 'Port Road'. It was Karachi's first great thoroughfare, linking the harbour to the growing city. Renamed after Muhammad Ali Jinnah, it runs from Merewether Tower past colonial landmarks such as the KMC Building and Denso Hall, all the way to the Mazar-e-Quaid.",
      "Trams once rattled along its length. Karachi's tramway opened in 1885 and ran, in one form or another, until 1975.",
      "It is also the city's stage. Muharram processions, political rallies and protests all make their way along M.A. Jinnah Road, and the crowds can stretch for kilometres.",
    ],
    facts: [
      ['Old name', 'Bunder Road'],
      ['Trams', '1885–1975'],
      ['Landmarks', 'KMC Building, Denso Hall'],
    ],
    didYouKnow:
      'The domed building with the clock tower is the KMC Building, completed in 1932. It is still the headquarters of the city government.',
  },
  {
    id: 'shahrah-e-faisal',
    name: 'Shahrah-e-Faisal',
    urdu: 'شاہراہِ فیصل',
    category: 'street',
    area: 'Saddar to the airport',
    pos: [130, 48],
    radius: 24,
    model: 'billboards',
    tagline: 'The artery that carries the city to the airport.',
    body: [
      "Shahrah-e-Faisal runs for roughly 18 km from Saddar to the airport and is Karachi's main highway. It used to be called Drigh Road and was renamed in the 1970s after King Faisal of Saudi Arabia. Along the way you pass the Finance & Trade Centre, the PAF Museum, Karsaz, Nursery and a long parade of hotels, malls and billboards.",
      "On 18 October 2007 Benazir Bhutto returned to Pakistan after eight years in exile, and her homecoming procession crawled along this road. Near Karsaz, two bombs exploded among the crowds and killed around 180 people. She survived, only to be assassinated in Rawalpindi two months later.",
      'At rush hour it is a river of rickshaws, buses, motorbikes and cars, and at night it glows with lit-up billboards. Every Karachiite has a story about being stuck on Shahrah-e-Faisal.',
    ],
    facts: [
      ['Old name', 'Drigh Road'],
      ['Length', 'about 18 km'],
      ['Named after', 'King Faisal of Saudi Arabia'],
    ],
    didYouKnow:
      'The PAF Museum on Shahrah-e-Faisal displays dozens of real fighter jets and aircraft in its gardens, which makes it a favourite day out for families.',
  },
  {
    id: 'tariq-road',
    name: 'Tariq Road',
    urdu: 'طارق روڈ',
    category: 'street',
    area: 'PECHS',
    pos: [85, 61],
    radius: 22,
    model: 'tariqRoad',
    tagline: 'Where Karachi shops for Eid.',
    body: [
      "Tariq Road runs through PECHS (the Pakistan Employees Co-operative Housing Society), which was set up soon after Partition to house government workers. It is one of the city's busiest shopping streets, selling fabric, shoes, bridal wear, bangles, perfume and crockery.",
      "In the last days of Ramadan, and above all on Chaand Raat, the night the Eid moon is sighted, the street turns into a carnival. Shops stay open until dawn, families hunt for last-minute outfits, and girls queue to have mehndi (henna) painted on their hands.",
      "Big malls such as Dolmen Mall have arrived, one of them on Tariq Road itself, but the street's small shops and haggling culture are still going strong.",
    ],
    facts: [
      ['Neighbourhood', 'PECHS'],
      ['Known for', 'Clothes, shoes, Eid shopping'],
      ['Busiest night', 'Chaand Raat'],
    ],
    didYouKnow:
      'The road is named after Tariq ibn Ziyad, the 8th-century commander who led the Muslim conquest of Spain. Gibraltar (Jabal Tariq, "Tariq\'s Mountain") is named after him too.',
  },
  {
    id: 'zamzama',
    name: 'Zamzama Boulevard',
    urdu: 'زمزمہ',
    category: 'street',
    area: 'DHA Phase 5',
    pos: [82, -116],
    radius: 20,
    model: 'zamzama',
    tagline: "Cafés, boutiques and Karachi's see-and-be-seen strip.",
    body: [
      "Zamzama Boulevard in Defence is lined with designer boutiques, cafés, galleries and restaurants. This is where the city's fashion labels open their flagship stores, and where friends meet for a cup of chai that costs ten times what it would at a roadside dhaba.",
      "It is also a window onto Karachi's inequality. A short drive away, families share a single water tap, while shoppers here buy bridal outfits that cost more than a year's wages.",
      'Zamzama Park at one end is a favourite with joggers and families on cooler evenings.',
    ],
    facts: [
      ['Neighbourhood', 'DHA Phase 5'],
      ['Known for', 'Boutiques, cafés, galleries'],
      ['Best time', 'Evenings'],
    ],
    didYouKnow:
      "Many of Pakistan's best-known fashion designers started out with small studios around Zamzama before going international.",
  },

  // ─────────────────────────────── Food ───────────────────────────────
  {
    id: 'burns-road',
    name: 'Burns Road',
    urdu: 'برنس روڈ',
    category: 'food',
    area: 'Old City',
    pos: [-100, 4],
    radius: 20,
    model: 'burnsRoad',
    tagline: "The capital of Karachi's late-night food.",
    body: [
      "After Partition, many families from Delhi settled in this part of the old city and brought their kitchens with them. Burns Road has been famous ever since for Delhi-style food: slow-cooked nihari, haleem, bun kebabs, chicken tikka, fried fish, rabri and kulfi.",
      "The street is lined with old colonial buildings with stone fronts and wooden balconies, many of them now crumbling above the busy shopfronts. In the evening plastic tables spill onto the pavement and the air fills with smoke from the grills.",
      'Generations of Karachiites have argued here about who makes the best nihari, and families still come from across the city to settle the question.',
    ],
    facts: [
      ['Famous for', 'Nihari, haleem, rabri, bun kebab'],
      ['Best time', 'After dark'],
      ['Food style', 'Dilliwala (Delhi)'],
    ],
    didYouKnow:
      "Nihari takes its name from the Arabic word nahar, meaning 'morning'. It was originally eaten after the dawn prayer, though in Karachi it is just as popular at midnight.",
  },
  {
    id: 'boat-basin',
    name: 'Boat Basin',
    urdu: 'بوٹ بیسن',
    category: 'food',
    area: 'Clifton',
    pos: [8, -92],
    radius: 20,
    model: 'boatBasin',
    tagline: 'Late-night food stalls with a side of sea breeze.',
    body: [
      'Boat Basin is a Clifton food street named after an old basin where boats used to moor, and it comes alive after dark.',
      "Karachi eats late, and Boat Basin is where you see it happening. Families turn up at 11 pm, students split a plate of chicken karahi, barbecue smoke curls over the parked cars, and waiters run trays out to people who never leave their vehicles.",
      "Classic orders include seekh kebab, chicken tikka, paratha rolls, bun kebab, falooda, and a cup of doodh patti chai to finish.",
    ],
    facts: [
      ['Best time', 'After 10 pm'],
      ['Order', 'Rolls, BBQ, falooda'],
      ['Car service', 'Yes, food comes to your window'],
    ],
    didYouKnow:
      "The paratha roll, kebab or tikka wrapped in a flaky, buttery paratha, is often credited as a Karachi invention. It is now sold all over Pakistan.",
  },
  {
    id: 'port-grand',
    name: 'Port Grand',
    urdu: 'پورٹ گرینڈ',
    category: 'food',
    area: 'Native Jetty',
    pos: [-190, -64],
    radius: 22,
    model: 'portGrand',
    tagline: 'Food and harbour views on a colonial bridge.',
    body: [
      "Port Grand was built along the old Native Jetty Bridge, which since the 1850s has linked the city to Keamari across the harbour. In 2011 a stretch of it opened as an open-air food and entertainment complex about a kilometre long.",
      "Here you can eat looking straight out over the harbour, with its ships, cranes, mangroves along the creek, and the lights of Keamari. There is also a banyan tree on the site that is said to be centuries old.",
      "It has opened and closed several times over the years, but on a cool evening it is one of the few places in the city where you can sit right next to the water.",
    ],
    facts: [
      ['Opened', '2011'],
      ['Built on', 'Native Jetty Bridge (1850s)'],
      ['Length', 'about 1 km'],
    ],
    didYouKnow:
      "Karachi's mangrove forests, which you can see from Port Grand, protect the coast from storms and act as nurseries for many of the fish and prawns that end up on the city's plates.",
  },
  {
    id: 'do-darya',
    name: 'Do Darya',
    urdu: 'دو دریا',
    category: 'food',
    area: 'DHA Phase 8',
    pos: [226, -176],
    radius: 24,
    model: 'doDarya',
    tagline: 'Seafood on a deck over the Arabian Sea.',
    body: [
      "At the far end of Defence's seafront, a row of restaurants sits on platforms over the water. Do Darya is where Karachi comes for grilled fish, prawns and karahi, with waves breaking a few metres below.",
      'On a breezy evening the decks fill with families and friends, the sky turns orange over the sea, and the lights of passing ships blink on the horizon.',
      "It is one of the newer parts of the city, built on land DHA reclaimed from the sea, and a sign of how Karachi keeps pushing its coastline outward.",
    ],
    facts: [
      ['Location', 'DHA Phase 8 seafront'],
      ['Known for', 'Seafood and sunsets'],
      ['Name means', '"Two rivers"'],
    ],
    didYouKnow:
      "Karachi's favourite fish include pomfret, surmai (kingfish) and red snapper, and many restaurants let you pick your fish before it goes on the grill.",
  },

  // ─────────────────────────── Sea & Shore ───────────────────────────
  {
    id: 'sea-view',
    name: 'Sea View (Clifton Beach)',
    urdu: 'سی ویو',
    category: 'sea',
    area: 'Clifton / DHA',
    pos: [40, -142],
    radius: 26,
    model: 'seaView',
    tagline: 'Camels, corn on the cob and the Arabian Sea.',
    body: [
      "Clifton Beach, better known as Sea View, is Karachi's great public space. On weekends and holidays tens of thousands of people come to walk on the sand, ride camels and horses, eat roasted corn (bhutta), and let the waves soak their shalwars.",
      "During the monsoon the sea turns rough, and swimming is regularly banned after drownings. The beach also carries scars. In 2003 the oil tanker Tasman Spirit ran aground off Karachi and spilled tens of thousands of tonnes of crude, fouling the shore for months.",
      "Nearby is the restored Jehangir Kothari Parade, a 1920s seaside promenade paid for by a Parsi philanthropist, which looks out over the sand.",
    ],
    facts: [
      ['Things to do', 'Camel rides, bhutta, kites'],
      ['Best time', 'Sunset'],
      ['Monsoon', 'Swimming often banned'],
    ],
    didYouKnow:
      'The camels at Sea View are decorated almost as brightly as the rickshaws, with tassels, mirror-work and embroidered saddles.',
  },
  {
    id: 'hawkes-bay',
    name: "Hawke's Bay",
    urdu: 'ہاکس بے',
    category: 'sea',
    area: 'West coast',
    pos: [-376, -56],
    radius: 24,
    model: 'hawkesBay',
    tagline: 'Quiet beaches and nesting sea turtles.',
    body: [
      "West of the city, beyond Mauripur, the coast opens into the long sandy beaches of Hawke's Bay and Sandspit. Families rent beach huts for the day, and the water is calmer and cleaner than at Sea View.",
      'These beaches are among the most important nesting sites for green sea turtles in the region. From roughly September to January, females haul themselves up the sand at night to lay their eggs, and conservationists from the Sindh Wildlife Department and WWF-Pakistan guard the nests and help the hatchlings reach the sea.',
      'Development and pollution threaten the beach. Still, on a quiet evening, watching hatchlings scramble toward the waves, it feels a world away from the city.',
    ],
    facts: [
      ['Wildlife', 'Green sea turtles'],
      ['Nesting season', 'Roughly Sept–Jan'],
      ['Nearby', 'Sandspit, Manora'],
    ],
    didYouKnow:
      'Only around one in a thousand sea turtle hatchlings is thought to survive to adulthood, which is why every protected nest matters.',
  },
  {
    id: 'manora',
    name: 'Manora',
    urdu: 'منوڑا',
    category: 'sea',
    area: 'Harbour mouth',
    pos: [-255, -174],
    radius: 24,
    model: 'manora',
    tagline: 'A lighthouse, a temple and a fort at the mouth of the harbour.',
    body: [
      "Manora is the peninsula that guards the entrance to Karachi's harbour. It is joined to the mainland by the long Sandspit, but most people get there by a short ferry ride from Keamari. Its lighthouse, built in 1889, has guided ships into Karachi for well over a century.",
      'In 1839 British warships bombarded the small fort on Manora, and Karachi surrendered without much of a fight. That was the beginning of British rule over the city.',
      "Manora is also home to the Shri Varun Dev Mandir, a temple around a century old dedicated to Varuna, the Hindu god of the sea. Karachi's Hindu community has been working to restore it.",
    ],
    facts: [
      ['Lighthouse', '1889'],
      ['Getting there', 'Ferry from Keamari'],
      ['History', 'British landing, 1839'],
    ],
    didYouKnow:
      'The ferry from Keamari to Manora passes right through the busy harbour, between fishing boats, tugs and cargo ships. It is one of the cheapest boat rides in the country.',
  },
  {
    id: 'karachi-port',
    name: 'Karachi Port',
    urdu: 'کراچی بندرگاہ',
    category: 'sea',
    area: 'Keamari',
    pos: [-248, -92],
    radius: 24,
    model: 'port',
    tagline: 'The reason Karachi became a great city.',
    body: [
      "Karachi grew from a fishing village into Pakistan's largest city because of its natural harbour. The British captured it in 1839 and developed the port to ship out cotton and wheat from Sindh and Punjab, and the Karachi Port Trust was founded in 1887.",
      "Today Karachi Port and the newer Port Qasim to the east handle most of Pakistan's sea trade. Container ships and tankers queue offshore while cranes swing boxes onto trucks that then rumble up-country.",
      'Those trucks are famous in their own right. They are covered in Pakistani truck art, with painted flowers, poetry, portraits and jingling chains, and that is the style this game borrows for its rickshaws.',
    ],
    facts: [
      ['Port Trust founded', '1887'],
      ['Sheltered by', 'Manora'],
      ['Handles', "Most of Pakistan's sea trade (with Port Qasim)"],
    ],
    didYouKnow:
      'Legend says Karachi takes its name from Mai Kolachi, a fisherwoman whose village stood beside this harbour.',
  },

  // ─────────────────────────── Neighbourhoods ───────────────────────────
  {
    id: 'saddar',
    name: 'Saddar',
    urdu: 'صدر',
    category: 'neighbourhood',
    area: 'Central Karachi',
    pos: [-80, 22],
    radius: 22,
    model: null,
    tagline: 'The old downtown of colonial stone, electronics and glorious chaos.',
    body: [
      "Saddar grew up in the 19th century as the bazaar of the British cantonment, and for a hundred years it was Karachi's downtown. Its streets are lined with stone buildings with balconies and carved details, put up by Parsi, Goan, Hindu and Muslim merchants.",
      "Today you come here for almost anything: electronics and mobile phones, textbooks and second-hand books, clothes at Zainab Market, fabric at Bohri Bazaar and spices at Empress Market. Rickshaws, buses and pedestrians fight for every inch.",
      'Saddar is full of traces of a more cosmopolitan city: churches, a Parsi fire temple, old cinemas and cafés, and buildings with the names of their original owners carved above the doors.',
    ],
    facts: [
      ['Known for', 'Empress Market, electronics, books'],
      ['Began as', 'Cantonment bazaar, 1800s'],
      ['Getting around', 'On foot, very patiently'],
    ],
    didYouKnow:
      "Karachi's Parsi community, tiny today, built many of the city's schools, hospitals and parks. It also gave Karachi its first elected mayor, Jamshed Nusserwanjee Mehta.",
  },
  {
    id: 'clifton',
    name: 'Clifton',
    urdu: 'کلفٹن',
    category: 'neighbourhood',
    area: 'South Karachi',
    pos: [-10, -108],
    radius: 22,
    model: null,
    tagline: 'A seaside neighbourhood of mansions, shrines and sunsets.',
    body: [
      "Clifton began as a breezy seaside retreat for colonial Karachi and became one of the city's most desirable addresses. Mohatta Palace, the shrine of Abdullah Shah Ghazi, Teen Talwar, Bahria Icon Tower and the beach at Sea View are all here.",
      "It is deeply political too. 70 Clifton is the Bhutto family home, where Zulfikar Ali Bhutto and later Benazir Bhutto lived, and where generations of party workers and journalists have gathered.",
      'Its streets mix old bungalows, high-rise apartments, malls such as Dolmen Mall, and vendors selling everything from coconut water to kites.',
    ],
    facts: [
      ['Landmarks', 'Teen Talwar, Mohatta Palace, the shrine'],
      ['Famous address', '70 Clifton'],
      ['Feel', 'Breezy, busy, upmarket'],
    ],
    didYouKnow:
      'Bilawal House, the current residence of the Bhutto-Zardari family and a centre of Pakistan Peoples Party politics, is also in Clifton.',
  },
  {
    id: 'dha',
    name: 'DHA (Defence)',
    urdu: 'ڈیفنس',
    category: 'neighbourhood',
    area: 'South-east Karachi',
    pos: [165, -88],
    radius: 26,
    model: null,
    tagline: 'Wide avenues, big houses, and an army-run property empire.',
    body: [
      "The Defence Housing Authority began in the 1950s as a housing society for military officers. It has grown into one of Karachi's wealthiest areas, with eight 'phases' stretching along the coast.",
      "Its grid of wide avenues, called khayabans, and its villas behind high walls stand in sharp contrast to the dense neighbourhoods inland. It has its own rules, security and administration, and it is run by the military.",
      "DHA is part of a bigger story about the Pakistani military's vast property and business interests. Critics argue these give the military outsized economic power, while residents often point to the order and services DHA provides.",
    ],
    facts: [
      ['Began', '1950s, as an officers\' housing society'],
      ['Phases', '8'],
      ['Landmarks', 'Tooba Mosque, Do Darya, Zamzama'],
    ],
    didYouKnow:
      "Defence's avenues all have grand Persian-style names, such as Khayaban-e-Ittehad ('Avenue of Unity') and Khayaban-e-Shamsheer ('Avenue of the Sword').",
  },
  {
    id: 'lyari',
    name: 'Lyari',
    urdu: 'لیاری',
    category: 'neighbourhood',
    area: 'West Karachi',
    pos: [-160, 82],
    radius: 26,
    model: 'lyariFootball',
    tagline: "Karachi's oldest neighbourhood: football, boxing and resilience.",
    body: [
      'Lyari is older than the British city. Its Baloch, Sindhi and Kutchi families have lived along the Lyari River for centuries, many of them working as fishermen, dockworkers and labourers in the port.',
      "It is the heartland of Pakistani football, sometimes called 'Pakistan's little Brazil', and it has produced many of the country's footballers and boxers, including the Olympic bronze medallist Hussain Shah. Benazir Bhutto held her public wedding reception at Lyari's Kakri Ground in 1987, a sign of how central the area was to her Pakistan Peoples Party.",
      'From the 2000s, gang wars involving figures such as Rehman Dakait and later Uzair Baloch tore through Lyari, until a paramilitary-led operation began in 2013. Since then residents have worked hard to reclaim its image, and young people are telling Lyari\'s story through football clubs, boxing gyms, music, rap, cafés and art.',
    ],
    facts: [
      ['Communities', 'Baloch, Sindhi, Kutchi and more'],
      ['Famous for', 'Football and boxing'],
      ['Nickname', "Pakistan's little Brazil"],
    ],
    didYouKnow:
      "When Brazil play at the World Cup, Lyari's streets fill with yellow-and-green flags, and big screens go up in the lanes.",
  },
  {
    id: 'keamari',
    name: 'Keamari',
    urdu: 'کیماڑی',
    category: 'neighbourhood',
    area: 'Port',
    pos: [-278, -66],
    radius: 22,
    model: null,
    tagline: 'Docks, fishing boats and the way to Manora.',
    body: [
      "Keamari is Karachi's port neighbourhood. It has wharves, warehouses, fuel depots, the fish harbour, and the jetty where ferries leave for Manora and boats head out on night-time crabbing trips.",
      'Many residents come from fishing communities, especially the Sindhi and Baloch Mohana and Mallah families who have worked these waters for generations.',
      "It is also on the front line of the city's environmental problems. In 2020 a mysterious toxic gas leak in Keamari killed more than a dozen people, and its waters carry much of the city's untreated sewage and industrial waste out to sea.",
    ],
    facts: [
      ['Known for', 'Port, fish harbour, ferries'],
      ['Night out', 'Crabbing boat trips'],
      ['Communities', 'Mohana, Mallah, Baloch and more'],
    ],
    didYouKnow:
      'On a night-time crabbing trip from Keamari, the crabs are caught, cooked and eaten on the boat. It is a classic Karachi outing.',
  },
  {
    id: 'gulshan-e-iqbal',
    name: 'Gulshan-e-Iqbal',
    urdu: 'گلشنِ اقبال',
    category: 'neighbourhood',
    area: 'East Karachi',
    pos: [168, 190],
    radius: 26,
    model: null,
    tagline: 'The middle-class heart of the city.',
    body: [
      "Gulshan-e-Iqbal ('Iqbal's Garden', named after the poet Allama Muhammad Iqbal) was laid out by the Karachi Development Authority in the 1960s and 70s as the city spread north-east. It is now one of Karachi's biggest and busiest middle-class areas.",
      'It is a jumble of apartment blocks, markets, schools and tuition centres, with University Road running through it towards NED University and the University of Karachi. Aladdin amusement park and Millennium Mall are weekend favourites.',
      "Like much of Karachi it lives with chronic water shortages. Water tankers are a constant sight, and the rooftop water tanks you see everywhere in this game are a very real feature of the city.",
    ],
    facts: [
      ['Named after', 'Allama Iqbal'],
      ['Developed', '1960s–70s'],
      ['Landmarks', 'Civic Centre, Aladdin Park, Safari Park'],
    ],
    didYouKnow:
      "Karachi's 'tanker mafia', private water tankers selling water that ought to arrive through the pipes, has been a political scandal for years.",
  },
  {
    id: 'nazimabad',
    name: 'Nazimabad',
    urdu: 'ناظم آباد',
    category: 'neighbourhood',
    area: 'Central Karachi',
    pos: [-66, 196],
    radius: 26,
    model: null,
    tagline: 'A planned town built for the refugees of Partition.',
    body: [
      "After 1947, hundreds of thousands of Muslim refugees from India arrived in Karachi, and the city's population more than doubled within a few years. Nazimabad was one of the first planned housing schemes built for them, and it is named after Khawaja Nazimuddin, Pakistan's second Governor-General and later Prime Minister.",
      "Its Urdu-speaking families, known as Muhajirs ('migrants'), shaped Karachi's identity, culture and politics. Nearby North Nazimabad and Federal B. Area later became strongholds of the MQM, whose headquarters, known as 'Nine Zero', stood in neighbouring Azizabad.",
      'Today Nazimabad is dense and lively, with old government quarters, markets, schools and close-knit mohallas where neighbours have known each other for generations.',
    ],
    facts: [
      ['Founded', 'Early 1950s'],
      ['Named after', 'Khawaja Nazimuddin'],
      ['Nearby', 'North Nazimabad, Federal B. Area'],
    ],
    didYouKnow:
      "Karachi's population grew from around 450,000 in 1941 to over a million by 1951. Today it is home to well over 20 million people.",
  },
  {
    id: 'orangi-town',
    name: 'Orangi Town',
    urdu: 'اورنگی ٹاؤن',
    category: 'neighbourhood',
    area: 'North-west Karachi',
    pos: [-250, 232],
    radius: 30,
    model: null,
    tagline: "One of Asia's largest informal settlements, and a world model of self-help.",
    body: [
      "Orangi Town spreads across the hills of north-west Karachi. It grew from the 1960s as an informal settlement, built by migrants from all over Pakistan and by Bihari families displaced by the 1971 war that created Bangladesh. It is often described as one of the largest katchi abadis (informal settlements) in Asia.",
      "In 1980 the social scientist Akhtar Hameed Khan founded the Orangi Pilot Project (OPP). Rather than wait for the government, the residents of each lane organised, paid for and built their own sewer lines, with OPP providing technical help. The model has been studied and copied around the world.",
      "In 2013 Perween Rahman, who led OPP's work mapping land and informal settlements in Karachi, was shot dead in Orangi. Her research on land-grabbing had made her powerful enemies, and her murder became a symbol of the dangers facing activists in the city.",
    ],
    facts: [
      ['Grew from', '1960s'],
      ['Famous for', 'Orangi Pilot Project (1980)'],
      ['Population', 'Well over a million (estimates vary)'],
    ],
    didYouKnow:
      "OPP's lane-by-lane approach let residents build their drains for a fraction of what government contractors would have charged.",
  },
  {
    id: 'korangi',
    name: 'Korangi',
    urdu: 'کورنگی',
    category: 'neighbourhood',
    area: 'East Karachi',
    pos: [345, -52],
    radius: 28,
    model: null,
    tagline: 'Factories, mangroves, and a township designed by a Greek planner.',
    body: [
      "In the late 1950s, General Ayub Khan's government moved refugees out of inner-city camps into a new township at Korangi. It was planned by the Greek architect Constantinos Doxiadis, who also designed Islamabad.",
      'Korangi grew into one of Karachi\'s main industrial zones, home to textile mills, tanneries, pharmaceutical plants and countless workshops. It is a huge employer, and also a major source of the pollution that flows into Korangi Creek.',
      'Along the creek, mangrove forests survive between the factories and the sea, sheltering birds and fish and helping to protect the coast.',
    ],
    facts: [
      ['Township', 'Late 1950s'],
      ['Planner', 'Constantinos Doxiadis'],
      ['Known for', 'Industry, Korangi Creek'],
    ],
    didYouKnow:
      "Doxiadis designed Korangi as a model of modern living, with neighbourhoods built around schools and markets, but Karachi's breakneck growth quickly overwhelmed the plan.",
  },
];
